version: 2
updates:
  - package-ecosystem: "poetry"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
      directory: "/"
      schedule:
        interval: "weekly"
